#!/usr/bin/perl

use 5.010;
use strict;
use warnings;

print "Enter Farenheit temp: ";
	our $TempF = <STDIN>;
	
sub TempCelsius{
	$TempF = @_;
	our $tempC = (($TempF - 32)/1.8);
	print $tempC;
	}
our $tempC = (($TempF - 32)/1.8);
print "$tempC\n";



